name: Python CI/CD

on:
  push:
    branches:
      - "main"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"

concurrency:
  group: python-cicd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-setup-uv@v7
        with:
          enable-cache ${{ !env.ACT }}  # If not locally run with 'act', enable cache

      - name: Sync project
        run: uv sync --locked --all-extras --dev

      - name: Run Tests
        run: uv run pytest
